### ISSUE TITLE
"bcrypt" still mandatory to run the tests

### ISSUE THREAD

**Issue by henning-schild** [Kozea/Radicale#1699]
Starting from 3.4.0 'bcrypt' is an optional dependency at runtime. However it seems to still be mandatory to successfully run the tests.

Just ran into that on gentoo here https://bugs.gentoo.org/949850

The gentoo solution will likely be to add bcrypt as a build dependency when testing is enabled.

Just wanted to let you know. Maybe the tests can be changed so that bcrypt related tests are skipped gracefully when not available.

**Comment by pbiering** [comment]
fixed by https://github.com/Kozea/Radicale/pull/1700

**Comment by henning-schild** [comment]
Thanks!

**Comment by henning-schild** [comment]
Just wondering if https://github.com/Kozea/Radicale/blob/93970a1001abfb085897324306ff99457e8f0fad/pyproject.toml#L40 needs changing as well

**Comment by pbiering** [comment]
> Just wondering if
> 
> [Radicale/pyproject.toml](https://github.com/Kozea/Radicale/blob/93970a1001abfb085897324306ff99457e8f0fad/pyproject.toml#L40)
> 
> Line 40 in [93970a1](/Kozea/Radicale/commit/93970a1001abfb085897324306ff99457e8f0fad)
>  test = ["pytest>=7", "waitress", "bcrypt"] 
> needs changing as well

In this context:

```
[project.optional-dependencies]
test = ["pytest>=7", "waitress", "bcrypt"]
bcrypt = ["bcrypt"]
ldap = ["ldap3"]
```

I would assume it's not causing any problems now.

**Comment by henning-schild** [comment]
With 3.5.0 and no "bcrypt" installed i still get failed tests.

```
FAILED radicale/tests/test_auth.py::TestBaseAuthRequests::test_htpasswd_plain_autodetect - UnboundLocalError: cannot access local variable 'bcrypt' where it is not associated with a value
FAILED radicale/tests/test_auth.py::TestBaseAuthRequests::test_htpasswd_md5_autodetect - UnboundLocalError: cannot access local variable 'bcrypt' where it is not associated with a value
FAILED radicale/tests/test_auth.py::TestBaseAuthRequests::test_htpasswd_sha256_autodetect - UnboundLocalError: cannot access local variable 'bcrypt' where it is not associated with a value
FAILED radicale/tests/test_auth.py::TestBaseAuthRequests::test_htpasswd_sha512_autodetect - UnboundLocalError: cannot access local variable 'bcrypt' where it is not associated with a value
```

**Comment by henning-schild** [comment]
please reopen

**Comment by pbiering** [comment]
looks like using "tox" for testing had somehow hidden that issue, finally solved now in code.
